<?php

return [
    [
        "title" => "Florence Elegance",
        "n_rooms" => 3,
        "n_beds" => 4,
        "n_bathrooms" => 2,
        "squared_meters" => 75,
        "image" => "bnb_images/bnb-1.jpg",
        "description" => "Situato nel cuore di Roma, a pochi passi dal Colosseo e dalle boutique di alta moda, offre un'esperienza di soggiorno unica con tutti i comfort di una casa moderna e lo charme di un palazzo storico.",
        "address" => "Via dei Fori Imperiali 13, 00184 Roma",
        "latitude" => 41.8925,
        "longitude" => 12.4873,
        "slug" => "florence-elegance",
        "user_id" => 1
    ],
    [
        "title" => "Venice Luxury Suite",
        "n_rooms" => 2,
        "n_beds" => 3,
        "n_bathrooms" => 1,
        "squared_meters" => 60,
        "image" => "bnb_images/bnb-2.jpg",
        "description" => "Immerso nei vicoli storici di Roma, Venice Luxury Suite offre un rifugio elegante con vista mozzafiato e accesso privato a monumenti storici, per un'esperienza romana autentica.",
        "address" => "Via Ceresio 26, 00199 Roma",
        "latitude" => 41.926504,
        "longitude" => 12.508638,
        "slug" => "venice-luxury-suite",
        "user_id" => 1
    ],
    [
        "title" => "Milan Central Apartment",
        "n_rooms" => 4,
        "n_beds" => 5,
        "n_bathrooms" => 3,
        "squared_meters" => 90,
        "image" => "bnb_images/bnb-3.jpg",
        "description" => "Nel cuore del centro storico di Roma, questo appartamento offre ampi spazi, arredi moderni e tutte le comodità necessarie per un soggiorno di lavoro o di piacere.",
        "address" => "Via Valle di Corio 6, 00141 Roma",
        "latitude" => 41.940092,
        "longitude" => 12.527387,
        "slug" => "milan-central-apartment",
        "user_id" => 1
    ],
    [
        "title" => "Naples Seaside Loft",
        "n_rooms" => 1,
        "n_beds" => 2,
        "n_bathrooms" => 1,
        "squared_meters" => 55,
        "image" => "bnb_images/bnb-4.jpg",
        "description" => "Nel cuore di Trastevere, questo loft offre un'esperienza unica con viste panoramiche sul Tevere e un'atmosfera accogliente e raffinata.",
        "address" => "Via Paolo Monelli 11, 00139 Roma",
        "latitude" => 41.962076,
        "longitude" => 12.549713,
        "slug" => "naples-seaside-loft",
        "user_id" => 1
    ],
    [
        "title" => "Rome Garden Suite",
        "n_rooms" => 2,
        "n_beds" => 3,
        "n_bathrooms" => 2,
        "squared_meters" => 70,
        "image" => "bnb_images/bnb-5.jpg",
        "description" => "Situato nei pressi di Villa Borghese, Rome Garden Suite offre un soggiorno rilassante con accesso diretto ai giardini e una posizione privilegiata per esplorare i tesori di Roma.",
        "address" => "Via della Marcigliana, 00139 Roma",
        "latitude" => 41.991700,
        "longitude" => 12.560288,
        "slug" => "rome-garden-suite",
        "user_id" => 1
    ],
    [
        "title" => "Casine Liberty Futurista",
        "n_rooms" => 1,
        "n_beds" => 1,
        "n_bathrooms" => 1,
        "squared_meters" => 70,
        "image" => "bnb_images/bnb-6.jpg",
        "description" => "Pied a terre appena ristrutturato, nuovo, pieno di colori futuristi  e liberty. Atmosfere fatte di divertimento, gioco, belle donne e humour  care al Lupin che è in te. Nel silenzio di un attico di un palazzo razionalista italiano anni '30, godrai un'atmosfera originale, bevendo con la tua complice un buon flute di bollicine o abbronzandoti in terrazzo.",
        "address" => "Via di Tor S. Giovanni 301, 00139 Roma",
        "latitude" => 42.0005937,
        "longitude" => 12.585127,
        "slug" => "casine-liberty-futurista",
        "user_id" => 1
    ],
    [
        "title" => "Casa Kico",
        "n_rooms" => 2,
        "n_beds" => 3,
        "n_bathrooms" => 1,
        "squared_meters" => 90,
        "image" => "bnb_images/bnb-7.jpg",
        "description" => "La cura per il design e l'attenzione per i particolari hanno permesso di creare un ambiente molto accogliente dove sarà piacevole trascorrere il vostro tempo.
        Ogni dettaglio, dai mobili alla cucina, il soggiorno, le camere da letto e il bagno sono completamente nuovi, garantendo un'esperienza di soggiorno impeccabile.
        L'appartamento è situato a piazza Bologna, in una posizione centrale e strategica.",
        "address" => "Via Cesa di Loreto 110, 00013 Roma",
        "latitude" => 42.024260,
        "longitude" => 12.615303,
        "slug" => "casa-kico",
        "user_id" => 1
    ],
    [
        "title" => "My Rental Inn",
        "n_rooms" => 2,
        "n_beds" => 3,
        "n_bathrooms" => 2,
        "squared_meters" => 95,
        "image" => "bnb_images/bnb-8.jpg",
        "description" => "Appartamento ristrutturato situato al quarto piano in una delle zone più eleganti di Roma, in prossimità della famosa via Veneto, e del grande giardino di Villa Borghese...ideale per gli amanti dello sport e delle passeggiate all'aperto. Grazie alla posizione strategica si raggiungono a piedi, velocemente, sia Fontana di Trevi che Piazza di Spagna.",
        "address" => "Via Dora Baltea 51, 00013 Roma",
        "latitude" => 42.040606,
        "longitude" => 12.644837,
        "slug" => "my-rental-inn",
        "user_id" => 1
    ],
    [
        "title" => "Saint Peter Dome",
        "n_rooms" => 3,
        "n_beds" => 3,
        "n_bathrooms" => 1,
        "squared_meters" => 110,
        "image" => "bnb_images/bnb-9.jpg",
        "description" => "L'appartamento si trova nel centro di Roma, vicinissimo alla Città del Vaticano e alla basilica di San Pietro. È possibile ammirare la magnificenza della cupola di San Pietro dal balcone dell'appartamento.
        Lo staff della “Cupola di San Pietro” sarà lieto di ospitare e accogliere gli ospiti affinché vivano un'esperienza indimenticabile a Roma.",
        "address" => "Località la Ficorella, 00015 Roma",
        "latitude" => 42.070145,
        "longitude" => 12.668517,
        "slug" => "saint-peter-dome",
        "user_id" => 1
    ],
    [
        "title" => "Domus Britannia",
        "n_rooms" => 2,
        "n_beds" => 4,
        "n_bathrooms" => 1,
        "squared_meters" => 100,
        "image" => "bnb_images/bnb-10.jpg",
        "description" => "Benvenuti nel nostro incantevole attico nel cuore del quartiere San Giovanni, che dispone di due accoglienti camere da letto, una cucina completamente attrezzata, un bagno confortevole e una sala da pranzo accogliente con comodo divano letto, offrendo spazio per un massimo di 7 ospiti. Esplorate le meraviglie di Roma, facilmente raggiungibili a piedi così come la stazione della metro e varie fermate dell'autobus nelle vicinanze. Godete del tramonto dal nostro balcone con vista San Pietro!",
        "address" => "Via Auriga 6, 00018 Roma",
        "latitude" => 42.098410,
        "longitude" => 12.646183,
        "slug" => "domus-britannia",
        "user_id" => 1
    ],
];
